"""
Content models for SAMVAAD AI
Defines request/response schemas for content generation, translation, and engagement
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class Platform(str, Enum):
    """Supported social media platforms"""
    INSTAGRAM = "instagram"
    TWITTER = "twitter"
    LINKEDIN = "linkedin"
    FACEBOOK = "facebook"
    AMAZON = "amazon"


class ContentStatus(str, Enum):
    """Content workflow status"""
    DRAFT = "draft"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    SCHEDULED = "scheduled"


class ContentVariant(BaseModel):
    """A single content variant generated by AI"""
    variant_id: str = Field(..., description="Unique identifier for the variant")
    content: str = Field(..., description="Generated content text")
    hashtags: List[str] = Field(default_factory=list, description="Suggested hashtags")
    emojis: List[str] = Field(default_factory=list, description="Emojis used in content")
    engagement_score: Optional[float] = Field(None, description="Predicted engagement score")
    is_selected: bool = Field(default=False, description="Whether this variant is selected")
    
    class Config:
        json_schema_extra = {
            "example": {
                "variant_id": "var_001",
                "content": "Celebrate Diwali with our exclusive collection! ✨🪔",
                "hashtags": ["#Diwali2024", "#FestivalOfLights", "#MadeInIndia"],
                "emojis": ["✨", "🪔"],
                "engagement_score": 85.5,
                "is_selected": False
            }
        }


class ContentRequest(BaseModel):
    """Request model for content generation"""
    prompt: str = Field(..., min_length=10, max_length=1000, description="Content generation prompt")
    platform: Platform = Field(..., description="Target social media platform")
    language: str = Field(default="en", description="Content language code")
    tone: Optional[str] = Field(default="professional", description="Content tone")
    cultural_context: Optional[str] = Field(None, description="Cultural context for content")
    target_audience: Optional[str] = Field(None, description="Target audience description")
    include_hashtags: bool = Field(default=True, description="Whether to include hashtags")
    include_emojis: bool = Field(default=True, description="Whether to include emojis")
    max_variants: int = Field(default=3, ge=1, le=5, description="Number of variants to generate")
    
    class Config:
        json_schema_extra = {
            "example": {
                "prompt": "Create a promotional post for our Diwali sale on handmade crafts",
                "platform": "instagram",
                "language": "en",
                "tone": "festive",
                "cultural_context": "diwali",
                "target_audience": "young professionals interested in Indian crafts",
                "include_hashtags": True,
                "include_emojis": True,
                "max_variants": 3
            }
        }


class ContentResponse(BaseModel):
    """Response model for content generation"""
    content_id: str = Field(..., description="Unique content identifier")
    prompt: str = Field(..., description="Original prompt")
    platform: Platform = Field(..., description="Target platform")
    variants: List[ContentVariant] = Field(..., description="Generated content variants")
    status: ContentStatus = Field(default=ContentStatus.DRAFT, description="Content status")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional metadata")


class TranslationRequest(BaseModel):
    """Request model for content translation"""
    content: str = Field(..., min_length=1, max_length=5000, description="Content to translate")
    source_language: str = Field(default="en", description="Source language code")
    target_language: str = Field(..., description="Target language code")
    preserve_emojis: bool = Field(default=True, description="Preserve emojis during translation")
    preserve_hashtags: bool = Field(default=True, description="Preserve hashtags during translation")
    preserve_formatting: bool = Field(default=True, description="Preserve text formatting")
    
    class Config:
        json_schema_extra = {
            "example": {
                "content": "Happy Diwali! 🪔✨ Celebrate with our exclusive collection. #FestivalOfLights",
                "source_language": "en",
                "target_language": "hi",
                "preserve_emojis": True,
                "preserve_hashtags": True,
                "preserve_formatting": True
            }
        }


class TranslationResponse(BaseModel):
    """Response model for content translation"""
    original_content: str = Field(..., description="Original content")
    translated_content: str = Field(..., description="Translated content")
    source_language: str = Field(..., description="Source language")
    target_language: str = Field(..., description="Target language")
    confidence_score: float = Field(..., description="Translation confidence score")
    preserved_elements: Dict[str, List[str]] = Field(
        default_factory=dict, 
        description="Elements preserved during translation"
    )


class EngagementFactors(BaseModel):
    """Breakdown of engagement prediction factors"""
    timing: float = Field(..., ge=0, le=100, description="Timing score")
    hashtags: float = Field(..., ge=0, le=100, description="Hashtag effectiveness score")
    content_quality: float = Field(..., ge=0, le=100, description="Content quality score")
    cultural_relevance: float = Field(..., ge=0, le=100, description="Cultural relevance score")
    sentiment: float = Field(..., ge=0, le=100, description="Sentiment score")


class EngagementRequest(BaseModel):
    """Request model for engagement prediction"""
    content: str = Field(..., min_length=1, max_length=5000, description="Content to analyze")
    platform: Platform = Field(..., description="Target platform")
    hashtags: List[str] = Field(default_factory=list, description="Hashtags in content")
    posting_time: Optional[datetime] = Field(None, description="Planned posting time")
    target_audience: Optional[str] = Field(None, description="Target audience")
    
    class Config:
        json_schema_extra = {
            "example": {
                "content": "Celebrate Diwali with handmade crafts! ✨🪔 #Diwali #MadeInIndia",
                "platform": "instagram",
                "hashtags": ["#Diwali", "#MadeInIndia"],
                "posting_time": "2024-11-01T18:30:00Z",
                "target_audience": "young professionals"
            }
        }


class EngagementResponse(BaseModel):
    """Response model for engagement prediction"""
    score: float = Field(..., ge=0, le=100, description="Overall engagement score")
    confidence: float = Field(..., ge=0, le=1, description="Prediction confidence")
    factors: EngagementFactors = Field(..., description="Score breakdown by factors")
    recommendations: List[str] = Field(default_factory=list, description="Improvement suggestions")
    predicted_reach: Optional[int] = Field(None, description="Predicted reach")
    predicted_likes: Optional[int] = Field(None, description="Predicted likes")
    optimal_posting_times: List[str] = Field(default_factory=list, description="Best times to post")


class ApprovalRequest(BaseModel):
    """Request model for content approval"""
    content_id: str = Field(..., description="Content ID to approve/reject")
    variant_id: str = Field(..., description="Selected variant ID")
    action: str = Field(..., pattern="^(approve|reject)$", description="Approval action")
    feedback: Optional[str] = Field(None, description="Reviewer feedback")
    schedule_time: Optional[datetime] = Field(None, description="Scheduled publish time")
    
    class Config:
        json_schema_extra = {
            "example": {
                "content_id": "content_123",
                "variant_id": "var_001",
                "action": "approve",
                "feedback": "Great content, approved for publishing",
                "schedule_time": "2024-11-01T18:30:00Z"
            }
        }


class ApprovalResponse(BaseModel):
    """Response model for content approval"""
    content_id: str = Field(..., description="Content ID")
    status: ContentStatus = Field(..., description="New content status")
    approved_at: Optional[datetime] = Field(None, description="Approval timestamp")
    scheduled_time: Optional[datetime] = Field(None, description="Scheduled publish time")
    message: str = Field(..., description="Status message")


class HistoryFilter(BaseModel):
    """Filter model for content history"""
    platform: Optional[Platform] = Field(None, description="Filter by platform")
    status: Optional[ContentStatus] = Field(None, description="Filter by status")
    start_date: Optional[datetime] = Field(None, description="Start date for range")
    end_date: Optional[datetime] = Field(None, description="End date for range")
    limit: int = Field(default=50, ge=1, le=100, description="Number of items to return")
    offset: int = Field(default=0, ge=0, description="Pagination offset")


class HistoryItem(BaseModel):
    """A single history item"""
    content_id: str
    prompt: str
    platform: Platform
    status: ContentStatus
    selected_content: Optional[str] = None
    engagement_score: Optional[float] = None
    created_at: datetime
    published_at: Optional[datetime] = None
    metrics: Optional[Dict[str, Any]] = None


class HistoryResponse(BaseModel):
    """Response model for content history"""
    items: List[HistoryItem] = Field(..., description="History items")
    total: int = Field(..., description="Total number of items")
    limit: int = Field(..., description="Items per page")
    offset: int = Field(..., description="Current offset")
    has_more: bool = Field(..., description="Whether more items exist")
